### ISSUE TITLE
TextInput doesn't allow to change height

### ISSUE THREAD

**Issue by roy1210** [SwingbyProtocol/pulsar#14]
I'd like to change the `height` of `TextInput` to 46px - 56px. 
But looks like this `textInput` is not able to adjust height size. Kindly please allow to change the height by css.

https://github.com/SwingbyProtocol/explorer/blob/config/201102/initial-setup/src/components/Explorer/ExplorerMain.styles.ts#L30

https://github.com/SwingbyProtocol/explorer/blob/config/201102/initial-setup/src/components/Explorer/ExplorerMain.styles.ts#L30

**Comment by tarrio** [comment]
The `<TextInput />` component supports 3 heights: 56, 48 and 40px as shown below.

```tsx
<TextInput size="country" />
```

```tsx
<TextInput size="state" />
```

```tsx
<TextInput size="city" />
```

<img width="358" alt="Screenshot 2020-11-05 at 14 43 54" src="https://user-images.githubusercontent.com/73276750/98248530-5b665580-1f75-11eb-9025-cb691de6c9f1.png">

**Comment by roy1210** [comment]
Noted, it's working. Thank you.
